### ISSUE TITLE
 Microsoft.ContainerService/managedClusters deployment issue

### ISSUE THREAD

**Issue by liuzhiyong1982** [mspnp/aks-baseline-regulated#44] opened 2021-10-14 20:51 UTC
When I attempt to deploy Microsoft.ContainerService/managedClusters in cluster-stamp.json file, I keep getting below error:
{
    "status": "Failed",
    "error": {
        "code": "ProvisioningControlPlaneError",
        "message": "AKS encountered an internal error while attempting the requested Updating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID: c6db0728-d434-46c4-b7eb-a7da3a34fdd6, Operation ID: 62887834-93d8-4efd-a2a9-0fb5f72445fe, Timestamp: 2021-10-14T18:34:04Z."
    }
}
What does it mean?

**Comment by ckittel** [comment] 2021-11-03 14:37
Unfortunately, based on this log entry, there is not enough data to know for sure @liuzhiyong1982.  When you get errors that look like this (e.g. `ProvisioningControlPlaneError`), usually customer support can get access to control plane logs to help diagnose the root cause.  Could be anything from a managed identity assignment that didn't complete, to a transient issue, to resource allocation issue on the VMSSs.  That error is pretty much a catch-all for a lot of situations that only customer support would have the ability to dive into.

**Comment by ckittel** [comment] 2021-11-30 14:57
No updates in about a month, so I'm going to close this one out.  You can reopen or start a new issue if the `ProvisioningControlPlaneError` is still a problem for you and the instructions above were helpful or understood. Cheers.

**Closed by ckittel** 2021-11-30 14:57 UTC
